version: '3.8'

services:
  app:
    build: .
    container_name: sistema_legado_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    # --- ESTA PARTE Ã‰ CRUCIAL ---
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Passa a senha do .env para o PHP
      - MYSQL_DATABASE=${MYSQL_DATABASE}           # Passa o nome do banco para o PHP

  db:
    image: mysql:5.7
    container_name: sistema_legado_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  db_data: